start-spacetime:
	spacetime start

publish-to-spacetime:
	spacetime publish --server local blackholio

generate-client-pipeline:
	spacetime generate --lang csharp --out-dir ../client-unity/Assets/autogen